### ISSUE TITLE
Something i dont understand 

### ISSUE THREAD

**Issue by USBhost** [mhagger/git-imerge#107] opened 2016-09-22 06:39 UTC
../git-imerge/git-imerge start --name=v3.10.102 --goal=full v3.10.102
Traceback (most recent call last):
  File "../git-imerge/git-imerge", line 3926, in <module>
    main(sys.argv[1:])
  File "../git-imerge/git-imerge", line 3895, in main
    cmd_start(parser, options)
  File "../git-imerge/git-imerge", line 3066, in cmd_start
    parser.error('%s\nPerhaps use "--first-parent"?', e)
TypeError: error() takes exactly 2 arguments (3 given)

---

../git-imerge/git-imerge merge v3.10.102
Commit "326a1b2d50cbe1f890e56ab60b9215cd30053f5a" is not a first-parent ancestor of "tmp-testing"

---

../git-imerge/git-imerge start --name=v3.10.102 --goal=full --first-parent v3.10.102
Commit "326a1b2d50cbe1f890e56ab60b9215cd30053f5a" is not a first-parent ancestor of "tmp-testing"

is there something i'm missing?

i reverted everything back to e8da000b925562cc34941079cd74fd4a1ae51de1 to make it work again.

**Comment by mhagger** [comment] 2016-09-23 14:19
@USBhost: Thanks for the report. `parser.error()` simply wasn't being called correctly. I just pushed a fix as #108. Would you be able to check this version in the situation where you experienced the error, just to make sure that I didn't make another boneheaded mistake, before I merge it?

**Comment by USBhost** [comment] 2016-09-23 21:08
will do

**Comment by USBhost** [comment] 2016-09-24 01:14
is there anymore i can help with?

**Comment by mhagger** [comment] 2016-09-25 06:41
@USBhost: thanks for fixing my fix. I just pushed your changes to #108 and merged that PR.

I misunderstood this bug report to be about the crash due to the problems fixed in #108. In fact, your problem seems to be that `git-imerge` legitimately can't handle merging/rebasing from one branch point to another if those commits are not connected by a chain of `--first-parent` ancestry. This is currently a limitation of `git-imerge` that could probably be relaxed under some circumstances. I'll reopen this issue as an enhancement request.

**Comment by mhagger** [comment] 2016-09-25 06:43
Also, if I understand correctly, this apparently worked in earlier versions of `git-imerge`.

I don't have much time to follow up on this now, I'm afraid.

**Comment by USBhost** [comment] 2016-09-25 08:19
Ever since https://github.com/mhagger/git-imerge/commit/26d4f9a41ff64183539b1ddc18522bf944e5b2c3
It won't work

It would be nice to ad an force option to make it go anyway.

**Comment by kergoth** [comment] 2016-09-26 15:38
I have the same problem. This is a pretty clear regression in functionality, not an enhancement. I'm reverting too.

**Comment by mhagger** [comment] 2016-09-28 10:07
There is another good description of this problem, with an ASCII-art diagram even,  in https://github.com/mhagger/git-imerge/issues/110#issue-179482601.

**Comment by mhagger** [comment] 2016-09-28 11:55
I can't stand having users forced to use old versions due to a regression :broken_heart:, so I tried to fix this problem after all. I think that #111 fixes this regression and also makes `git-imerge` applicable in many more situations that it didn't handle correctly even before e8da000b925562cc34941079cd74fd4a1ae51de1.

The problem is that my time is really tight right now, so I'm going to need your help. I did a tiny bit of manual testing, but this is an important spot in the code that is used for all imerges (not only in the case that the merge-base is not a first-parent ancestor of the branch tips). If somebody could do more careful testing that #111 hasn't broken anything, or even better, improve the test suite to verify the current code and catch any similar new regressions in the future, that would be a great help towards getting this fix merged and in general improving the quality of `git-imerge`. Anyone? :pray:

**Comment by USBhost** [comment] 2016-09-30 01:22
@mhagger  will do man 😂 
You commit got lost in my email

**Comment by kergoth** [comment] 2016-10-06 23:12
I doubt I'd have time to write unit tests, myself, but as feedback, #111 works for me in the one repo where I use imerge on a regular basis (maintaining long-lived release branches). Thanks much for your work on this. I'll keep using the version from #111 and see if I run into any issues. Hopefully one of the other folks with this issue can do more testing than I.

**Comment by dregad** [comment] 2016-11-21 16:26
For the record, I faced the same issue trying to imerge mantisbt mantisbt/mantisbt@5d2f72a95c0397a2abc936736f0437bc0e553166 (*master-1.3.x* branch) into mantisbt/mantisbt@67f2bd428af37fd8863c33691b811273ab9f35bb (*master* branch).

Reverting to 0.7.0 fixed the problem for now; I'll test your proposed fix later as time allows.

**Comment by cproensa** [comment] 2016-12-11 16:19
I could perform a merge with the #111 code, in the same scenario as @dregad reported

**Closed** 2016-12-16 08:41 UTC
Labels: enhancement
